modLoader="javafml"
loaderVersion="[41,)"
license="MIT Lisence"
[[mods]]
modId="copperation"
version="${0.1-1.19}"
displayName="Copperation"
logoFile="copperation.png"
credits="NarynotNarold, Carmenboy, DoltHHaven"
authors="Team Taiga Modding"
description='''
Copperation is a mod aiming to add a variety of copper related blocks and items, as well as modifying already
existing blocks to use copper in them.
'''
[[dependencies.copperation]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.copperation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.copperation]]
modId = "blueprint"
mandatory = true
versionRange = "[6.0.5,)"
ordering = "BEFORE"
side = "BOTH"
